### ISSUE TITLE
Scribe fails w/ helm deployment not named "scribe" on OpenShift

### ISSUE THREAD

**Issue by JohnStrunk** [backube/scribe#124]
**Describe the bug**
If Scribe is deployed via the Helm chart and the user provides a release name other than "scribe", the operator will fail to give access to the correct SCC.

**Steps to reproduce**
```
$ helm install --create-namespace scribe-system scribe-0000 backube/scribe
```
The ReplicationDestination will show the following error:
```
  status:
    conditions:
    - lastTransitionTime: "2021-02-22T21:28:47Z"
      message: |-
        roles.rbac.authorization.k8s.io "scribe-src-database-destination" is forbidden: user "system:serviceaccount:scribe-system:scribe-20886" (groups=["system:serviceaccounts" "system:serviceaccounts:scribe-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
        {APIGroups:["security.openshift.io"], Resources:["securitycontextconstraints"], ResourceNames:["scribe-mover"], Verbs:["use"]}
      reason: ReconcileError
      status: "False"
      type: Reconciled
```

The SCC gets named by the Helm chart according to the release name to disambiguate it, but that name is not passed to the operator. Instead the operator uses the fixed SCC name of `scribe-mover`.

**Expected behavior**

**Actual results**

**Additional context**

Workaround:
Install Scribe on OpenShift using a release name of "scribe":
```
$ helm install --create-namespace scribe-system scribe backube/scribe
```

The fix will be to add a CLI option to the operator so that the correct SCC name can be provided, defaulting to the current "scribe-mover"
