### ISSUE TITLE
Demo: sync data into kube

### ISSUE THREAD

**Issue by JohnStrunk** [backube/scribe#65]
**Describe the feature you'd like to have.**
We should put together a demo showing how to use Scribe to sync data into a kube cluster.

**What is the value to the end user? (why is it a priority?)**
- This will provide a concrete demonstration that Scribe can be used to help admins migrate their data into a Kubernetes environment.
- Mocking this up will also highlight areas where we can simplify the process.
  - Do we need helper scripts?
  - Does this highlight other usability issues?

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**

**Comment by cooktheryan** [comment]
with this are we expecting the external storage to be a storageclass within a cluster or completely external? @JohnStrunk @screeley44

**Comment by screeley44** [comment]
I think external, to show how Scribe can help get your data into a kube environment

**Comment by JohnStrunk** [comment]
Completely external.

Consider:
The IT department has a project to move application X from their legacy infrastructure into their shiny new Kubernetes environment.

We should be able to run periodic syncs (for staging/testing) prior to the final switchover. (I'm thinking of a cron entry on the external infra to drive this)

**Comment by cooktheryan** [comment]
Potential spec I am thinking
```
---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source
  namespace: source
spec:
  trigger:
    schedule: "*/3 * * * *"
  external:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: my.host.com
    sourceType: SSH
    path: /var/www/html

---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source
  namespace: source
spec:
  trigger:
    schedule: "*/3 * * * *"
  external:
    address: my.host.com
    Secret: secret (optional tls values)
    sourceType: gluster
    path: /brick1

---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source
  namespace: source
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/3 * * * *"
  external:
    address: my.host.com
    Secret: secret (ceph.conf + keyring)
    sourceType: cephrbd
    path: /cephfs
```

**Comment by cooktheryan** [comment]
For the destination, we most likely could get away with almost all of the same parameters that rsync operates with today

**Comment by JohnStrunk** [comment]
I was hoping this wouldn't require any changes to the CR or operator...
We could have a script/binary that runs on the external infrastructure and plays the role of the Source or Destination. Since it's just rsync over an ssh connection, those are commonly available across most platforms.
Imagine a script like:
```
./scribe-source --source /my/local/data --destination elb.cluster.com:22 --local-key my-ssh-key --remote-key other-key.pub
```
... that would connect to the Service created by a ReplicationDestination.
This script could be triggered via `at` or `cron` to create periodic syncs.
The local/remote keys would need to agree with the secretRef in the corresponding ReplicationDestination (either autogenerated or manually created would both work).

------

Moving data out may be even easier given the ReplicationSource for rsync. Assuming the external system has an ssh server:
```yaml
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: replicationsource-sample
spec:
  sourcePVC: pvcname
  trigger:
    schedule: "0 * * * *"  # hourly
  rsync:
    copyMethod: Clone
    sshKeys: secretRef
    address: my.external-system.com  # the external host that mounts the storage
    port: 22  # port that runs sshd
    sshUser: myusername  # username to use when connecting to the remote system
```

The above is generic, so we don't need to care what storage we're migrating from/to.
